### ISSUE TITLE
完全无效，没有保存到本地存储

### ISSUE THREAD

**Issue by tianbaop** [boenfu/vuex-along#11]
我按照方法引入而且设置好了，但是打开浏览器依然没有生效，刷新就没了，另一个项目引用成功了，但是清除不了

**Comment by boenfu** [comment]
请问你是怎么配置的呢 贴个图嘛。
你可以看看 demo 页面 都生效的。

**Comment by tianbaop** [comment]
------------------ 原始邮件 ------------------
发件人: "Boen"<notifications@github.com>;
发送时间: 2018年11月18日(星期天) 下午4:42
收件人: "boenfu/vuex-along"<vuex-along@noreply.github.com>;
抄送: "起风了"<1125282535@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [boenfu/vuex-along] 完全无效，没有保存到本地存储 (#11)




请问你是怎么配置的呢 贴个图嘛。
 你可以看看 demo 页面 都生效的。

**Comment by tianbaop** [comment]
![tim 20181118165220](https://user-images.githubusercontent.com/37539732/48670400-5aeb0f00-eb52-11e8-99f8-4887c1e4e168.png)

**Comment by tianbaop** [comment]
之前还用了vuexAlong.watch也无效就去掉了

**Comment by boenfu** [comment]
你设置好了 有设置state测试吗，
如果你的数据 在state初始化后  一次都没有改动过 ，
是不会存储的，因为那样也没有意义，

**Comment by tianbaop** [comment]
更改过的，这个我知道的嘛，
但是依然没有效果，我试了另一种方法也没有给我存储

**Comment by boenfu** [comment]
经过我刚刚测试，所有api均可正常使用
测试步骤
1.使用vue-cli 创建项目
2.安装 vuex vuex-along
3.编写sotre.js 及修改 测试所用的App.vue
[https://gist.github.com/boenfu/502dc13ded010e36a925638879a77848](https://gist.github.com/boenfu/502dc13ded010e36a925638879a77848)
