### ISSUE TITLE
Great plugin!

### ISSUE THREAD

**Issue by wangjun521** [boenfu/vuex-along#17]
tks!!! Just solved the module storage problem

**Comment by wangcheng1212** [comment]
安装的1.1.5的版本,报错"export 'default' (imported as 'vuexAlong') was not found in 'vuex-along'

**Comment by boenfu** [comment]
> 安装的1.1.5的版本,报错"export 'default' (imported as 'vuexAlong') was not found in 'vuex-along'

1.1.5 不再维护 😂
