### ISSUE TITLE
安装1.1.5的版本报错

### ISSUE THREAD

**Issue by wangcheng1212** [boenfu/vuex-along#18]
安装的1.1.5的版本,报错"export 'default' (imported as 'vuexAlong') was not found in 'vuex-along'

**Comment by wangcheng1212** [comment]
安装最新版本的,又会报index.js?91c9:79 Uncaught TypeError: Object(...) is not a function

**Comment by boenfu** [comment]
我想你是否需要这个
[https://stackoverflow.com/questions/51374678/es6-uncaught-typeerror-object-is-not-a-function](url)

**Comment by boenfu** [comment]
先关闭啦 有需要请再次打开
