### ISSUE TITLE
vue-cli打包出错

### ISSUE THREAD

**Issue by wangjun521** [boenfu/vuex-along#19]
版本1.2.3

2.x版本的vue-cli打包时并没有把插件的es6转为es5  导致在某些ios上直接报严格模式下const不支持  在将vuex-along 加入babel-loader的includes中后  在打包时直接报 
````
WARNING in ./node_modules/vuex-along/lib/main.js
62:31-32 "export 'default' (imported as '_') was not found in 'lodash'
````
在直接放置服务器上后报
````
Cannot read property 'defaultsDeep' of undefined
````

感觉lodash并没有被引入进去 如何解决啊 急

**Comment by boenfu** [comment]
有加 babel-polyfill，加个那个可能就行了

**Comment by wangjun521** [comment]
这是必加的，仍旧没用的

**Comment by boenfu** [comment]
唔 明天空了来模拟一下，我想可能你可以试下 把 lodash 加入 includes

**Comment by wangjun521** [comment]
那我今天到公司试一下

**Comment by wangjun521** [comment]
不行的哦

**Comment by boenfu** [comment]
电脑上只有 cli 3 的脚手架，build 出来 lodash 也被编译了的，感觉你可以去对比一下两个版本的打包配置

**Comment by zyxlk** [comment]
同样这个问题

**Comment by boenfu** [comment]
@zyxlk @wangjun521 
现已加上了 babel ，可以更新到 `1.2.4` 试试。注意引入方式有一点点变化哟
`import createVuexAlong from 'vuex-along'`

**Comment by boenfu** [comment]
如果没啥问题我就先关闭issue咯，随时可以再打开，如果各位有更好的兼容方案，欢迎提pr
