### ISSUE TITLE
感谢大佬写的插件，用起来很成功，但是npm run build时会报错

### ISSUE THREAD

**Issue by JasonHuoying** [boenfu/vuex-along#2]
![default](https://user-images.githubusercontent.com/31676365/38293419-f91bf49c-3819-11e8-9446-27e54c6a401f.jpg)

ERROR in main.e5d9577adfa8f2ff835a.js from UglifyJs
Unexpected token: name (unll) [main.e5d9577adfa8f2ff835a.js:5698,4]
因该是webpack在打包vue文件时没有成功转换ES6的语法；

找到js 文件
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
let unll,ll,sl,unsl;   -----------------------------------------------------------（5698行）
let onlySession = false;
const LOCALSTORAGE = 0,SESSIONSTORAGE = 1,KEY = 'vuex-along';
const ls = window.localStorage;
const ss = window.sessionStorage;

const vuexAlong = store => {
    initAlong(store);
    store.subscribe(function (mutation, state) {
        saveLocal(state);
        saveSession(state);
    })
}
试过关闭严格模式  .. ["es2015", { "modules": false }]..依然报错，请问下又出现这种情况吗，还是配置文件webpack.base.config.js少了什么

**Comment by liuxiaofan** [comment]
我也遇到这个问题，没解决

**Comment by JasonHuoying** [comment]
我找到了楼主的js 文件 ，然后把里面的ES6语法改回Es5,再打包就没报错了，nginx还没试
