### ISSUE TITLE
构建uat和prod是报错，构建测试包不报错

### ISSUE THREAD

**Issue by sungycc** [boenfu/vuex-along#25]
![image](https://user-images.githubusercontent.com/38499198/57347066-9a9ac700-7183-11e9-8086-2290fedee550.png)
这个转换过来的语法怎么还有对象的解构赋值

**Comment by sungycc** [comment]
这个问题导致开发环境在VIVO  X7、oppo A59S、oppor9m三种手机型号都打不开

**Comment by boenfu** [comment]
最近空了会看下 也欢迎提 pr 😀
