### ISSUE TITLE
刚开始用就报错了！Unexpected identifier

### ISSUE THREAD

**Issue by apony** [boenfu/vuex-along#27]
怎么回事啊 老哥 帮我看看呗
![微信图片_20190522101827](https://user-images.githubusercontent.com/33817895/58142789-00ef1180-7c7b-11e9-8ff5-c714ec7ef468.png)

**Comment by boenfu** [comment]
请参照 readme，您并没有以正确的姿势打开

```
import createVuexAlong from 'vuex-along'

export default new Vuex.Store({
  state:{...},
  modules:{...},
  plugins: [createVuexAlong()]
});
```
