### ISSUE TITLE
Md5Base64字符串作为存储数据顶层属性名能否设置成动态的？这个顶层的属性值会动态变化吗？

### ISSUE THREAD

**Issue by weixinfei123** [boenfu/vuex-along#28]
在目前的项目需求中，有引入第三方的模块，与第三方模块通信时取得是本地存储的数据，这个顶层的属性值能否去掉，直接sessionStorage.getItem（“例如app”）获取数据，不要顶层的属性

**Comment by boenfu** [comment]
一个作为存储 key 的字符串，通常都是固定的，就像数据库名一样。至于这个值 正常情况下 通过md5base64转换后是固定不变的，你只需要多取一层
