### ISSUE TITLE
vue-cli脚手架引入组件，打包时报错。

### ISSUE THREAD

**Issue by robin901118** [boenfu/vuex-along#35]
**问题描述：**
用npm引入该组件后，在开发环境是正常的，但是运行`npm run build`时报错，报错内容`ERROR in static/js/vendor.9d86f97577080abdf83d.js from UglifyJs`，网上查询了一下说是因为node_modules里某个组件还存在es6语法未转换成es5导致的uglifyJs无法压缩，于是我在vue.config.js（vue-cli3版本）中加入
```
  transpileDependencies: [
    "vuex-along"
  ],
```
之后打包正常了。

**期望：**
希望能够完全编译该组件

**Comment by xiebiao360** [comment]
感谢留下解决方案，我也遇到这个问题，柳暗花明，感谢！还是希望作者能够尽快修复这个问题，不胜感激

**Comment by boenfu** [comment]
已彻底解决 version 1.2.9
