### ISSUE TITLE
一使用这个插件页面就卡死了

### ISSUE THREAD

**Issue by china-live** [boenfu/vuex-along#37]
用的1.2.8、1.2.7也一样，引入这个插件后页面就卡住了，也没有任何报错或提示。
初步猜测是修改state值时引起的，不使用有没有其他人遇到这个问题。

**Comment by boenfu** [comment]
请贴一下你的插件配置，

**Comment by china-live** [comment]
![QQ截图20190906112208](https://user-images.githubusercontent.com/12002799/64398760-a7c7b400-d098-11e9-998d-bb80f4426bfe.png)
应该不是vuex-along的问题，我用另一个插件vuex-persist也有这个问题，具体现象为一调用
         this.$store.commit('setClientID', 'login')
改变了 state 时就卡死了，没有报错信息。

**Comment by china-live** [comment]
不是调用只有调用 this.$store.commit('setClientID', 'login') 有问题，是所有 this.$store.commit() 都这样

**Comment by boenfu** [comment]
https://iwillcalm.github.io/subsidy-m
这个演示页面在登录处用了下vuex-along，cli 是 3.0
https://github.com/iwillcalm/subsidy-m/blob/master/src/components/Login.vue#L28-L35
没有卡死的现象

**Comment by china-live** [comment]
![QQ截图20190906141411](https://user-images.githubusercontent.com/12002799/64405112-a4d8bd80-d0b0-11e9-81be-0002b50bcca8.png)
这个是登录页面，一调用this.$store.commit('setClientID', 'login') 这句后面的就执行不到了，this.loading = true 原本这句会让页面显示loading动画也不会出来

**Comment by china-live** [comment]
会不会跟 Store内的state 项太多有关，我的state 比较多

**Comment by china-live** [comment]
我把Store内state、mutations和actions都删除只留一个了，还是不行，我正在升级vuex版本，先前用的3.0.1 换成最新的3.1.1试下

**Comment by china-live** [comment]
还是不行，this.$store.dispatch() 也调不到actions内的方法

**Comment by boenfu** [comment]
如果你知道原因 或有新的发现 随意重开 issue ，先关啦
