### ISSUE TITLE
小程序下使用错误

### ISSUE THREAD

**Issue by zlf4865231** [boenfu/vuex-along#39]
![image](https://user-images.githubusercontent.com/37063413/70196383-80d65800-1743-11ea-8c13-9cb8041934f4.png)
![image](https://user-images.githubusercontent.com/37063413/70196416-98addc00-1743-11ea-962a-145148ae08d7.png)

**Comment by boenfu** [comment]
是因为 小程序环境 没有 localsotrge
加个这个 https://github.com/boenfu/vuex-along-wx-adapter
