### ISSUE TITLE
我在vuex 中保存一个route对象会出现这个错误： TypeError: Cannot convert a Symbol value to a string

### ISSUE THREAD

**Issue by sujiewen** [boenfu/vuex-along#43]
如果不使用vuexAlong 就没有问题的

代码是这样的：

this.$store.dispatch('tagsView/addView', this.$route)

store 下面代码是这样的
const actions = {
  addView({ dispatch }, view) {
    dispatch('addVisitedView', view)
    dispatch('addCachedView', view)
  },
  addVisitedView({ commit }, view) {
    commit('ADD_VISITED_VIEW', view)
  },
  addCachedView({ commit }, view) {
    commit('ADD_CACHED_VIEW', view)
  }
}

 commit('ADD_VISITED_VIEW', view)执行这个代码就会引起这个问题

<img width="1042" alt="截屏2020-12-24 下午5 24 47" src="https://user-images.githubusercontent.com/1973318/103078503-fb9f3900-460c-11eb-8f10-362b1cf3fe48.png">

**Comment by sujiewen** [comment]
<img width="1042" alt="截屏2020-12-24 下午5 24 47" src="https://user-images.githubusercontent.com/1973318/103078584-26898d00-460d-11eb-9f7b-f0b5e531d925.png">

**Comment by sujiewen** [comment]
vue.runtime.esm.js:619 [Vue warn]: Error in mounted hook: "TypeError: Cannot convert a Symbol value to a string"

found in

---> <TagsView> at src/layout/components/TagsView/index.vue
       <Layout> at src/layout/index.vue
         <App> at src/App.vue
           <Root>
warn @ vue.runtime.esm.js:619
logError @ vue.runtime.esm.js:1884
globalHandleError @ vue.runtime.esm.js:1879
handleError @ vue.runtime.esm.js:1839
invokeWithErrorHandling @ vue.runtime.esm.js:1862
callHook @ vue.runtime.esm.js:4219
insert @ vue.runtime.esm.js:3139
invokeInsertHook @ vue.runtime.esm.js:6346
patch @ vue.runtime.esm.js:6565
Vue._update @ vue.runtime.esm.js:3948
updateComponent @ vue.runtime.esm.js:4066
get @ vue.runtime.esm.js:4479
run @ vue.runtime.esm.js:4554
flushSchedulerQueue @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
flushCallbacks @ vue.runtime.esm.js:1906
Promise.then (async)
timerFunc @ vue.runtime.esm.js:1933
nextTick @ vue.runtime.esm.js:1990
queueWatcher @ vue.runtime.esm.js:4402
update @ vue.runtime.esm.js:4544
notify @ vue.runtime.esm.js:730
reactiveSetter @ vue.runtime.esm.js:1055
(anonymous) @ vue-router.esm.js:2932
(anonymous) @ vue-router.esm.js:2931
updateRoute @ vue-router.esm.js:2352
(anonymous) @ vue-router.esm.js:2206
(anonymous) @ vue-router.esm.js:2340
step @ vue-router.esm.js:1944
step @ vue-router.esm.js:1951
step @ vue-router.esm.js:1951
runQueue @ vue-router.esm.js:1955
(anonymous) @ vue-router.esm.js:2335
step @ vue-router.esm.js:1944
(anonymous) @ vue-router.esm.js:1948
(anonymous) @ vue-router.esm.js:2322
(anonymous) @ vue-router.esm.js:2070
(anonymous) @ vue-router.esm.js:2146
Promise.then (async)
(anonymous) @ vue-router.esm.js:2093
(anonymous) @ vue-router.esm.js:2114
(anonymous) @ vue-router.esm.js:2114
flatMapComponents @ vue-router.esm.js:2113
(anonymous) @ vue-router.esm.js:2049
iterator @ vue-router.esm.js:2300
step @ vue-router.esm.js:1947
step @ vue-router.esm.js:1951
step @ vue-router.esm.js:1951
(anonymous) @ vue-router.esm.js:1948
(anonymous) @ vue-router.esm.js:2322
_callee$ @ permission.js:30
tryCatch @ runtime.js:65
invoke @ runtime.js:303
prototype.<computed> @ runtime.js:117
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ permission.js:13
iterator @ vue-router.esm.js:2300
step @ vue-router.esm.js:1947
runQueue @ vue-router.esm.js:1955
confirmTransition @ vue-router.esm.js:2330
transitionTo @ vue-router.esm.js:2203
init @ vue-router.esm.js:2923
beforeCreate @ vue-router.esm.js:1271
invokeWithErrorHandling @ vue.runtime.esm.js:1854
callHook @ vue.runtime.esm.js:4219
Vue._init @ vue.runtime.esm.js:5004
Vue @ vue.runtime.esm.js:5085
./src/main.js @ main.js:94
__webpack_require__ @ bootstrap:848
fn @ bootstrap:150
1 @ index.vue?6416:1
__webpack_require__ @ bootstrap:848
checkDeferredModules @ bootstrap:45
(anonymous) @ bootstrap:924
(anonymous) @ bootstrap:924
Show 39 more frames
vue.runtime.esm.js:1888 TypeError: Cannot convert a Symbol value to a string
    at warnNonPresent (vue.runtime.esm.js:2016)
    at Object.has (vue.runtime.esm.js:2060)
    at baseGetTag (_baseGetTag.js:23)
    at baseClone (_baseClone.js:112)
    at _baseClone.js:161
    at arrayEach (_arrayEach.js:15)
    at baseClone (_baseClone.js:155)
    at _baseClone.js:161
    at arrayEach (_arrayEach.js:15)
    at baseClone (_baseClone.js:155)
logError @ vue.runtime.esm.js:1888
globalHandleError @ vue.runtime.esm.js:1879
handleError @ vue.runtime.esm.js:1839
invokeWithErrorHandling @ vue.runtime.esm.js:1862
callHook @ vue.runtime.esm.js:4219
insert @ vue.runtime.esm.js:3139
invokeInsertHook @ vue.runtime.esm.js:6346
patch @ vue.runtime.esm.js:6565
Vue._update @ vue.runtime.esm.js:3948
updateComponent @ vue.runtime.esm.js:4066
get @ vue.runtime.esm.js:4479
run @ vue.runtime.esm.js:4554
flushSchedulerQueue @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
flushCallbacks @ vue.runtime.esm.js:1906
Promise.then (async)
timerFunc @ vue.runtime.esm.js:1933
nextTick @ vue.runtime.esm.js:1990
queueWatcher @ vue.runtime.esm.js:4402
update @ vue.runtime.esm.js:4544
notify @ vue.runtime.esm.js:730
reactiveSetter @ vue.runtime.esm.js:1055
(anonymous) @ vue-router.esm.js:2932
(anonymous) @ vue-router.esm.js:2931
updateRoute @ vue-router.esm.js:2352
(anonymous) @ vue-router.esm.js:2206
(anonymous) @ vue-router.esm.js:2340
step @ vue-router.esm.js:1944
step @ vue-router.esm.js:1951
step @ vue-router.esm.js:1951
runQueue @ vue-router.esm.js:1955
(anonymous) @ vue-router.esm.js:2335
step @ vue-router.esm.js:1944
(anonymous) @ vue-router.esm.js:1948
(anonymous) @ vue-router.esm.js:2322
(anonymous) @ vue-router.esm.js:2070
(anonymous) @ vue-router.esm.js:2146
Promise.then (async)
(anonymous) @ vue-router.esm.js:2093
(anonymous) @ vue-router.esm.js:2114
(anonymous) @ vue-router.esm.js:2114
flatMapComponents @ vue-router.esm.js:2113
(anonymous) @ vue-router.esm.js:2049
iterator @ vue-router.esm.js:2300
step @ vue-router.esm.js:1947
step @ vue-router.esm.js:1951
step @ vue-router.esm.js:1951
(anonymous) @ vue-router.esm.js:1948
(anonymous) @ vue-router.esm.js:2322
_callee$ @ permission.js:30
tryCatch @ runtime.js:65
invoke @ runtime.js:303
prototype.<computed> @ runtime.js:117
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ permission.js:13
iterator @ vue-router.esm.js:2300
step @ vue-router.esm.js:1947
runQueue @ vue-router.esm.js:1955
confirmTransition @ vue-router.esm.js:2330
transitionTo @ vue-router.esm.js:2203
init @ vue-router.esm.js:2923
beforeCreate @ vue-router.esm.js:1271
invokeWithErrorHandling @ vue.runtime.esm.js:1854
callHook @ vue.runtime.esm.js:4219
Vue._init @ vue.runtime.esm.js:5004
Vue @ vue.runtime.esm.js:5085
./src/main.js @ main.js:94
__webpack_require__ @ bootstrap:848
fn @ bootstrap:150
1 @ index.vue?6416:1
__webpack_require__ @ bootstrap:848
checkDeferredModules @ bootstrap:45
(anonymous) @ bootstrap:924
(anonymous) @ bootstrap:924
Show 39 more frames

**Comment by sujiewen** [comment]
state.visitedViews.push(
      Object.assign({}, this.$route, {
        title: view.meta.title || 'no-name'
      })
    ) 这里深拷贝有问题

**Comment by boenfu** [comment]
这看上去是 $route 里有用 Symbol 做 key 的, 但我们存储的介质是 localstorage, 无法存储 Symbol

**Comment by sujiewen** [comment]
应该是$route里面有对象嵌套引起的

**Comment by GPX-NSlog** [comment]
> 应该是$route里面有对象嵌套引起的
@sujiewen 
怎么解决的

**Comment by 874910712** [comment]
> > 应该是$route里面有对象嵌套引起的
> > @sujiewen
> > 怎么解决的

我换了vuex-persistedstate插件就能解决了，是这个插件复制逻辑引起的，每次都是全部深度克隆整个state，state对象的属性中存储的某个对象有Symbol 做 key 的话，就会报错
