### ISSUE TITLE
打包的时候lodash不能被Tree shaking

### ISSUE THREAD

**Issue by wuyax** [boenfu/vuex-along#44]
打包以后通过webpack-bundle-analyzer分析发现lodash被完整的打包进了vendors.js。
`import { defaultsDeep, omit, pick, cloneDeep } from "lodash-es";`
替换为
`import  defaultsDeep from "lodash-es/defaultsDeep";`
可能是个更好的方案。

**Comment by boenfu** [comment]
蟹蟹啦，已更新

+ vuex-along@1.2.12
