### ISSUE TITLE
想问下可以增加数据加密存储嘛

### ISSUE THREAD

**Issue by CJH-1996** [boenfu/vuex-along#45]

**Comment by boenfu** [comment]
哈喽，简单写了个 [加密适配器](https://github.com/boenfu/vuex-along-secure-adapter#securels-adapter-for-vuex-along)
或许能解决你的需求，issue 我先关咯

**Comment by CJH-1996** [comment]
> 哈喽，简单写了个 [加密适配器](https://github.com/boenfu/vuex-along-secure-adapter#securels-adapter-for-vuex-along)
> 或许能解决你的需求，issue 我先关咯

厉害了 大佬 感谢
还有个问题是发现 
```js
import createVuexAlong from "vuex-along";

const dataState = createVuexAlong({
  // 设置保存的集合名字，避免同站点下的多项目数据冲突
  name: "hello-vuex-along",
  local: {
    list: ["test.num"],// 将test的num属性存储到local
  },
  session: {
    list: ["user"],// 将整个user存储到session
  },
});

const store = new Vuex.Store({
  modules,
  plugins: [dataState],
});
```
这样之后 只发现了清除所有状态的api  没有发现清除指定状态的api

**Comment by boenfu** [comment]
> > 哈喽，简单写了个 [加密适配器](https://github.com/boenfu/vuex-along-secure-adapter#securels-adapter-for-vuex-along)
> > 或许能解决你的需求，issue 我先关咯
> 
> 厉害了 大佬 感谢
> 还有个问题是发现
> 
> ```js
> import createVuexAlong from "vuex-along";
> 
> const dataState = createVuexAlong({
>   // 设置保存的集合名字，避免同站点下的多项目数据冲突
>   name: "hello-vuex-along",
>   local: {
>     list: ["test.num"],// 将test的num属性存储到local
>   },
>   session: {
>     list: ["user"],// 将整个user存储到session
>   },
> });
> 
> const store = new Vuex.Store({
>   modules,
>   plugins: [dataState],
> });
> ```
> 
> 这样之后 只发现了清除所有状态的api 没有发现清除指定状态的api

貌似没有清除指定状态的 api，直接通过 mutation 的方式无法满足需求么 0.0

**Comment by CJH-1996** [comment]
@boenfu  通过mutation设置state的值为空吗 👌 感谢
