### ISSUE TITLE
如果我想要配置属性嵌套应该如何

### ISSUE THREAD

**Issue by DevilRoshan** [boenfu/vuex-along#6]
例如：
`state={
     test:{
         test1:'test1',
         test2:'test2',
     }
}`

例如我只想不让test1持久化，应该如何配置，vuexAlong.watch (arry , [boolean])中的array好像并不能打到我的效果

**Comment by boenfu** [comment]
Sorry，这插件没有去变量对象的属性，所以没能帮到你；(╥╯^╰╥)
数量少的话可以自己覆盖了，或者把粒度写小点
